# name: Deploy React Frontend to Render

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'frontend/**'

# jobs:
#   deploy:
#     name: Build and Deploy Frontend
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: frontend

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install dependencies
#         run: npm ci

#       - name: Build the project
#         run: npm run build

#       - name: Deploy to Render
#         run: |
#           curl -X POST https://api.render.com/deploy/srv-xxxxxxxxxxxxxxxxxxxx?key=RENDER_API_KEY
