name: CI/CD - VocabPredictService

on:
  push:
    paths:
      - 'VocabPredictService/**'
      - '.github/workflows/deploy-vocabP-service.yml'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: ./VocabPredictService
        run: pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/vocabpredictservice:latest ./VocabPredictService

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/vocabpredictservice:latest

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Force new deployment of ECS service
        run: |
          aws ecs update-service \
            --cluster research-project-deploy \
            --service vocabpredictservicetaskone-service-6lbjt629 \
            --force-new-deployment
